export const LoginUrl = '/Portal/Mobile/LoginIn'
export const LoginOutUrl = '/Portal/Mobile/LoginOut'
export const GetWorkItems = '/Portal/Mobile/GetWorkItems' // 待办/已办
export const GetWorkCount = 'Portal/Mobile/GetWorkItemCount' // 待办/已办数量
export const GetReadItems = 'Portal/Mobile/LoadCirculateItems' // 待阅/已阅
export const BatchRead = 'Portal/Mobile/ReadCirculateItems' // 批量阅读
export const doingInstance = 'Portal/Mobile/myInstance/queryInstances' // 进行中
export const appList = 'Portal/Mobile/GetAppList' // 应用中心
export const appChildList = 'Portal/Mobile/GetFunctions' // 应用中心child
export const LoadWorkFlows = 'Portal/Mobile/LoadWorkflows' // 发起流程
export const LoadOrgTreeNodes = 'Portal/SheetUser/Mobile/LoadOrgTreeNodes' // 发起流程
export const WorkFlowsDetail = 'Portal/Mobile/getMvcDefaultSheet' // 流程详情
export const WorkFlowsUrl = 'Portal/WorkItemSheets/WorkItemSheets' // 流程url
export const DingTalkUrl = 'Portal/DingTalk/GetSignConfig' // 钉钉登录
